from setuptools import setup

with open('requirements.txt') as f:
    requirements = f.readlines()

long_description = 'Translate events from a Traktor S4 mk1 DJ controller \
                    generated by the linux snd-usb-caiaq kernel module to MIDI \
                    signals which can be used by virtual DJ software.'

setup(
    name='traktor-s4-mk1-midify',
    version='0.0.2',
    author='Conal Moloney',
    author_email='blaxpot@blax.site',
    url='https://github.com/blaxpot/traktor-s4-mk1-midify',
    description='Get MIDI signals from a Traktor S4 mk1 DJ controller under linux.',
    long_description=long_description,
    long_description_content_type="text/markdown",
    license='MIT',
    scripts=['midify.py'],
    entry_points={'console_scripts': ['traktor-s4-mk1-midify=midify:main', 'traktor-s4-mk1-print-events=midify:print_events']},
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Linux",
    ],
    keywords='native instruments traktor s4 mk1 linux',
    install_requires=requirements,
    zip_safe=False
)
